# pull recently build image node-pre-build

FROM node-pre-build

# A directory within the virtualized Docker environment
# Becomes more relevant when using Docker Compose later
WORKDIR /usr/src/app

# Installs test
RUN npm run test a