# pull recently build image my_node_app
FROM my_node_app

# A directory within the virtualized Docker environment
# Becomes more relevant when using Docker Compose later
WORKDIR /usr/src/app

# Installs test
RUN npm run test a